type LiteralUnion<T extends string | number> = T | Omit<T, T>;

export type Sizes = 'sm' | 'small' | 'md' | 'medium' | 'lg' | 'large';
export enum Colors {
	purple = 'purple',
	green = 'green',
	orange = 'orange',
	teal = 'teal',
	complementary = 'complementary',
	prime = 'prime'
}

export const volumes = ['low', 'medium', 'high'] as const;
export type Volume = typeof volumes[number];

export type ColorStrings = 'green' | 'purple' | 'teal' | 'orange';

export interface ThemeColors {
	purple?: ThemeObject;
	green?: ThemeObject;
	orange?: ThemeObject;
	teal?: ThemeObject;
	prime?: ThemeObject;
	complementary?: ThemeObject;
}

export interface ThemeObject {
	light?: string;
	100?: string;
	200?: string;
	300?: string;
	400?: string;
	500?: string;
	600?: string;
	700?: string;
	800?: string;
	900?: string;
	1000?: string;
	dark?: string;
	lightGradient?: string;
	mediumGradient?: string;
	darkGradient?: string;
}

export type Styles = {
	flexFlow?: string;
	gap?: string | number;
	alignItems?: string;
	width?: string;
	minHeight?: string;
	backgroundColor?: string;
	boxShadow?: LiteralUnion<Volume>;
	active?: Styles;
	height?: string;
	alignContent?: string;
	alignSelf?: string;
	all?: string;
	animation?: string;
	animationDelay?: string;
	animationDirection?: string;

	animationFillMode?: string;
	animationIterationCount?: string;
	animationName?: string;
	animationPlayState?: string;
	animationTimingFunction?: string;
	backgroundClip?: string;
	backgroundBlendMode?: string;
	backgroundImage?: string;
	backgroundOrigin?: string;
	backgroundPosition?: string;
	backgroundRepeat?: string;
	backgroundSize?: string;
	borderBottom?: string;
	borderBottomColor?: string;
	borderBottomLeftRadius?: string;
	borderBottomRightRadius?: string;
	borderBottomStyle?: string;
	borderBottomWidth?: string;
	borderCollapse?: string;
	borderImage?: string;
	borderImageOutset?: string;
	borderImageRepeat?: string;
	borderImageSource?: string;
	borderImageSlice?: string;
	borderImageWidth?: string;
	borderLeft?: string;
	borderLeftColor?: string;
	borderLeftStyle?: string;
	borderLeftWidth?: string;
	borderRadius?: string;
	borderRight?: string;
	borderRightColor?: string;
	borderRightStyle?: string;
	borderRightWidth?: string;
	borderSpacing?: string;
	borderStyle?: string;
	borderTop?: string;
	borderTopColor?: string;
	borderTopStyle?: string;
	borderTopWidth?: string;
	borderWidth?: string;
	boxSizing?: string;
	caretColor?: string;
	clipPath?: string;
	columnCount?: string;
	columnFill?: string;
	columnGap?: string;
	columnRule?: string;
	columnRuleColor?: string;
	columnRuleStyle?: string;
	columnRuleWidth?: string;
	counterIncrement?: string;
	counterReset?: string;
	emptyCells?: string;
	flexBasis?: string;
	flexDirection?: string;
	flexGrow?: string;
	flexShrink?: string;
	flexWrap?: string;
	fontFamily?: string;
	fontKerning?: string;
	fontSize?: string;
	fontSizeAdjust?: string;
	fontStretch?: string;
	fontStyle?: string;
	fontVariant?: string;
	fontWeight?: string;
	gridArea?: string;
	gridAutoColumns?: string;
	gridAutoFlow?: string;
	gridColumn?: string;
	gridColumnEnd?: string;
	gridColumnGap?: string;
	gridColumnStart?: string;
	gridTemplate?: string;
	gridTemplateAreas?: string;
	gridTemplateColumns?: string;
	gridTemplateRows?: string;
	justifyContent?: string;
	letterSpacing?: string;
	lineHeight?: string;
	listStyle?: string;
	listStyleImage?: string;
	listStylePosition?: string;
	listStyleType?: string;
	marginBottom?: string;
	marginLeft?: string;
	marginRight?: string;
	marginTop?: string;
	maxHeight?: string;
	maxWidth?: string;
	minWidth?: string;
	objectFit?: string;
	objectPosition?: string;
	outlineColor?: string;
	outlineOffset?: string;
	outlineStyle?: string;
	outlineWidth?: string;
	overflowX?: string;
	overflowY?: string;
	paddingBottom?: string;
	paddingLeft?: string;
	paddingRight?: string;
	paddingTop?: string;
	pageBreakAfter?: string;
	pageBreakBefore?: string;
	pageBreakInside?: string;
	perspectiveOrigin?: string;
	pointerEvents?: string;
	scrollBehavior?: string;
	tableLayout?: string;
	textAlign?: string;
	textAlignLast?: string;
	textDecoration?: string;
	textDecorationColor?: string;
	textDecorationLine?: string;
	textDecorationStyle?: string;
	textIndent?: string;
	textJustify?: string;
	textOverflow?: string;
	textShadow?: string;
	textTransform?: string;
	transformOrigin?: string;
	transformStyle?: string;
	transitionDelay?: string;
	transitionDuration?: string;
	transitionProperty?: string;
	transitionTimingFunction?: string;
	userSelect?: string;
	verticalAlign?: string;
	whiteSpace?: string;
	wordBreak?: string;
	wordSpacing?: string;
	wordWrap?: string;
	writingMode?: string;
	zIndex?: string;

	transition?: string;
	transform?: string;
	top?: string;
	right?: string;
	quotes?: string;
	position?: string;
	perspective?: string;
	padding?: string;
	overflow?: string;
	order?: string;
	outline?: string;
	opacity?: string;
	margin?: string;
	left?: string;
	hyphens?: string;
	grid?: string;
	float?: string;
	font?: string;
	direction?: string;
	display?: string;
	filter?: string;
	flex?: string;
	cursor?: string;
	content?: string;
	columns?: string;
	color?: string;
	clip?: string;
	clear?: string;
	bottom?: string;
	background?: string;
	border?: string;
};
