#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm run lint

BRANCH="$(git rev-parse --abbrev-ref HEAD)"
if [[ "$BRANCH" = "development" ]]; then
  echo 'Aborting script';
  exit 1;
fi

echo 'Do stuff';

npm test
npm run package
